services:
  be:
    build: ./be
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/workoutdb
      - SPRING_DATASOURCE_USERNAME=tkhoma
      - SPRING_DATASOURCE_PASSWORD=mypass
      - SPRING_PROFILES_ACTIVE=prod

  fe_desktop:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./fe:/home/node/app
    command: "npm run dev -- --host"
    depends_on:
      - be
  fe_mobile:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./fe_mobile:/home/node/app
    command: "npm run dev -- --host"
    depends_on:
      - be

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: workoutdb
      POSTGRES_USER: tkhoma
      POSTGRES_PASSWORD: mypass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - be
      - fe_desktop
      - fe_mobile
