server {
	listen 80;

	location / {
		if ($http_user_agent ~* "(android|iphone|ipad|ipod|mobile)") {
			proxy_pass http://fe_mobile:5173;   # mobile endpoint
		}

		if ($http_user_agent !~* "(android|iphone|ipad|ipod|mobile)") {
			proxy_pass http://fe_desktop:5173;   # desktop endpoint
		}

		proxy_set_header Host $host;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /api/ {
		proxy_pass http://be:8080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}
}
